project:
  type: website

language: 
  search-text-placeholder: "What would you like to know?"

website:
  title: "Transmission Channel Analysis"
  search: 
    location: navbar
    type: textbox
  navbar:
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: What is TCA?
      - text: Learn
    right: 
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    reference-location: margin
    citation-location: margin
    # include-before-body:
    #   - text: |
    #       <script type="text/javascript">document.getElementById("quarto-search").remove();</script>
    #       <link rel="preconnect" href="https://fonts.googleapis.com">
    #       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    #       <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&display=swap" rel="stylesheet">



