project:
  type: website

language: 
  search-text-placeholder: "What would you like to know?"

website:
  title: "Transmission Channel Analysis"
  page-navigation: true
  announcement: 
    icon: info-circle
    dismissable: false
    content: "**Note** - this website is still actively under construction."
    type: primary
    position: below-navbar
  search: 
    location: navbar
    type: textbox
  navbar:
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: Examples 
        href: "examples/index.qmd"
      - text: Documentation
        href: "documentation/index.qmd"
      - text: Wiki
        href: "faq/index.qmd"
    right: 
      - text: About
        href: "index.qmd#about"
  sidebar: 
    - id: doc
      title: Documentation
      contents: 
      - href: "documentation/index.qmd"
      - section: Julia 
        # href: "documentation/julia/index.qmd"
        contents: 
          - text: Overview
            href: "documentation/julia/index.qmd"
          - text: Advanced Tools
            href: "documentation/julia/advanced.qmd"
          - text: Internals
            href: "documentation/julia/internals.qmd"
          - section: All
            contents: documentation/julia/all-functions/*
      - section: Matlab
        # href: "documentation/matlab/index.qmd"
        contents: 
          - text: Overview
            href: "documentation/matlab/index.qmd"
          - text: Advanced Tools
            href: "documentation/matlab/advanced.qmd"
          - text: Internals
            href: "documentation/matlab/internals.qmd"
          - section: All
            contents: documentation/matlab/all-functions/*

    - id: faq
      title: Wiki
      contents:
        - section: Wiki
          contents: 
            - "faq/topics/what-is-tca.qmd"
            - "faq/topics/how-to-implement.qmd"
            - "faq/topics/dynamic-form.qmd"
            - "faq/topics/systems-form.qmd"
            - "faq/topics/graphical-form.qmd"
            - "faq/topics/boolean-conditions.qmd"

    - id: examples
      title: Examples
      contents: 
      - href: "examples/index.qmd"
      - section: Julia 
        contents: 
          - text: TCA in SVARs
            href: "examples/julia/svar/index.qmd"
          - text: TCA in LPs
            href: "examples/julia/lp/index.qmd"
      - section: Matlab
        contents: 
          - text: TCA in SVARs
            href: "examples/matlab/svar/index.qmd"
          - text: TCA in LPs
            href: "examples/matlab/lp/index.qmd"
          - text: TCA in DSGEs
            href: "examples/matlab/dynare/index.qmd"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    smooth-scroll: true



