project:
  type: website

language: 
  search-text-placeholder: "What would you like to know?"

website:
  title: "Transmission Channel Analysis"
  search: 
    location: navbar
    type: textbox
  navbar:
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: Tutorials 
      - text: Documentation
      - text: FAQ
    right: 
      - text: About
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    reference-location: margin
    citation-location: margin



