project:
  type: website

language: 
  search-text-placeholder: "What would you like to know?"

website:
  title: "Transmission Channel Analysis"
  page-navigation: true
  search: 
    location: navbar
    type: textbox
  navbar:
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: Tutorials 
      - text: Documentation
        href: "documentation/julia/index.qmd"
      - text: FAQ
        href: "faq/index.qmd"
    right: 
      - text: About
        href: about.qmd
  sidebar: 
    - id: doc
      title: Documentation
      contents: 
      - section: Julia 
        # href: "documentation/julia/index.qmd"
        contents: 
          - text: Overview
            href: "documentation/julia/index.qmd"
          - text: Internals
            href: "documentation/julia/internals.qmd"
          - text: All Symbols
            href: "documentation/julia/all-functions.qmd"
      - section: Matlab
        # href: "documentation/matlab/index.qmd"
        contents: 
          - text: Overview
            href: "documentation/matlab/index.qmd"
          - text: "Dynare DSGE"
            href: "documentation/matlab/dynare.qmd"
          - text: All Functions
            href: "documentation/matlab/all-functions.qmd"

    - id: faq
      title: FAQ
      contents: 
        - "faq/topics/what-is-tca.qmd"
        - "faq/topics/dynamic-form.qmd"
        - "faq/topics/systems-form.qmd"
        - "faq/topics/boolean-conditions.qmd"
        - "faq/topics/algebra.qmd"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    reference-location: margin
    citation-location: margin



