---
sidebar: doc
engine: julia
---

```{julia}
#| echo: false 
#| include: false 

using DocUtils
using JSON


function load_from_json(filename)
  dict = open(filename, "r") do file 
    JSON.parse(file)
  end
  return dict
end

functions = load_from_json("matlab-documentation-functions.json")
classes = load_from_json("matlab-documentation-classes.json")
class_methods = load_from_json("matlab-documentation-class-methods.json")
```

# Internals

The internals of the **Matlab Toolbox for Transmission Channel Analysis** all resolve around the type `Q`{.matlab}, which is the internal representation of a transmission condition using the variables of the [systems form](/faq/topics/systems-form.qmd); thus $x_i$ and **not** $y_{i,t}$.  


```{julia}
#| echo: false
#| output: asis

include_callout_block_matlab("Q", classes)
```

The basic idea is to start with a singleton statement, such as $x_i$, $\neg x_i$ or sometimes even just $\text{TRUE}$. Each of these singleton -- or atomic -- statements refers to the simplest transmission channel in which $x_i$ must be on the path, $x_i$ cannot be on the path, or in which case the condition is always true. Such singleton statement can be created in the following way. 

```{.matlab}
% x1 must be on the path
x1 = Q(1);

% x1 cannot be on the path
notX2 = Q('!x2');

% TRUE
T = Q('T');
```

More complex transmission conditions are then simply a combination of these singleton statements. More precisely, a transmission condition `q1`{.matlab} can be combined with another transmission condition `q2`{.matlab} using any of AND (`&`{.matlab}), OR (`|`{.matlab}) and NOT (`~`{.matlab})[^matlab-not]. Throughout, parentheses can be used to change the precedence. In the following we will describe how such combinations are internally implemented. 

[^matlab-not]: Note that Matlab uses `~` as the NOT operator. Internally we tend to use `!`. 

## Combining two conditions using AND (`&`{.matlab})

Suppose we wanted to combine two conditions `q1::Q`{.matlab} and `q2::Q`{.matlab} using an AND. Thus, suppose we wanted to do

```{.matlab}
q1 & q2
```

This is achieved by extending `and`{.matlab} for the type `Q`{.matlab}. However, key in the internal implementation is the following assumption. 

::: {#nte-assumption1-internal-julia .callout-note}
# Assumption 1

The transmission condition `q`{.matlab} consists of only conjunctions (`&`{.matlab}) and negations (`!`{.matlab}). 
:::

Under [Assumption @nte-assumption1-internal-julia] `q1`{.matlab} and `q2`{.matlab} both consist of only conjunctions and disjunctions. This immediately implies that their conjunction will also only consist of conjunctions and negations. We can thus simply "concatenate" the two conditions. This is basically what we internally do, with the caveat that the conditions are represented using `String`{.matlab} and that, for algorithimic purposes, we prefer the variables to be ordered in the statement. 

The detailed internal implementation is given by 

```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("Q", "and", class_methods)
```

While concatenating the two conditions, we need to watch out that no contradictions are being introduced. Contradictions are any statements along the lines $x_i \land \neg x_i$ which would always result in `false`{.matlab}. This is taken care of by the following functions. 

```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("checkContradiction", functions)
```

```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("removeContradictions", functions)
```

As stated in the [overview]("./index.qmd") of the documentation, removal of contradictions is governed by the global `REMOVECONTRADICTION`{.matlab} and the utility function `setRemoveContradictions`{.matlab}. Not removing contradictions does not lead to mistakes in the computation, but can result in longer computations. Contrary, removing contradictions can lead to longer compile times -- it takes longer to compile the transmission conditions. Thus, a trade-off between compile and computing time exists. 

```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("setRemoveContradictions", functions)
```

## Combining two conditions using OR (`|`{.matlab})

Let `q1`{.matlab} and `q2`{.matlab} be again two transmission conditions. Suppose their internal Boolean conditions are given by $b$ and $b'$ respectively, with both satisfying [Assumption @nte-assumption1-internal-julia]. The [rules for manipulating transmission conditions](/faq/topics/algebra.qmd) then imply
$$
Q(b \lor b') = Q(b) + Q(b') - Q(b \land b').
$$
Implementation of OR (`|`{.matlab}) therefore simply uses AND and the ability for `Q`{.matlab} to represent multiple terms with different multipliers. The precise implementation of OR can be found in the following function. 


```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("Q", "or", class_methods)
```

## Negating a condition using NOT (`~`{.matlab})

Suppose a transmission condition is given by `q`{.matlab} which internally represents the Boolean condition $b$. By the [rules for manipulating transmission conditions](/faq/topics/algebra.qmd) we then know that 
$$
Q(\neg b) = Q(T) - Q(b),
$$
where $T$ represents the Boolean condition that is always true. This can easily be represented using `Q`{.matlab} through its ability to represent multiple terms and multipliers. Specifically, we simply replace the original transmission condition with a new one that consists of one additional term, representing true, and switch the sign of all original terms of the condition. The following function implements this behaviour. 

```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("Q", "not", class_methods)
```

## Parsing transmission conditions using `makeCondition`{.matlab}

Rather than letting the user create all variables manually via `x1 = Q(1)`{.matlab} etc., we provide the function `makeCondition`{.matlab}. This function simply matches all variables in a string with the regex `x\d+`, creates the variables using the above way, and then evaluates the entire condition to create the final condition. Due to the operator overloading above, the final result will be a valid and correct transmission condtion. However, key to this correctness is that all variables match the provided regex pattern. Thus, all variables must be of the form `x1`, `x2`, etc. 

For user friendliness, we also provide a version of `makeConditionY`{.matlab} that takes variables of the [dynamic form](/faq/topics/dynamic-form.qmd), i.e. $y_{i,t}$. However, all that this function does is to translate all variables into variables of the [systems form](/faq/topics/systems-form.qmd) and then calls the method explained above. 

In any case, `makeCondition`{.matlab} and `makeConditionY`{.matlab} should be seen as utility functions with the main funcionality being dependent on correct implementation of `Q`{.matlab}, `&`{.matlab}, `|`{.matlab}, and `~`{.matlab} as explained above. 


```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("makeCondition", functions)
```

```{julia}
#| echo: false 
#| output: asis

include_callout_block_matlab("makeConditionY", functions)
```
