--- 
title: | 
  calculateQAndOnly
sidebar: doc
---

::: {.doc-box}
::: {.callout-warning appearance="simple" icon="false" collapse="true"}    
# calculateQAndOnly


`calculateQAndOnly` Compute the transmission effect of a condition with only ANDs.

`result = calculateQAndOnly(from, irfs, irfsOrtho, vars, multiplier)`
calculates the transmission effect of a transmission condition/query
that involves only AND operations.

## Arguments
- `from` (integer): Index of the shock.
- `irfs` (matrix): IRFs in transmission form. See also `toTransmissionIrfs`.
- `irfsOrtho` (matrix): Orthogonalized / Cholesky IRFs in transmission form.
See also `toTransmissionIrfs`.
- `vars` (vector of integers): Indices of variables involved in the condition.
- `multiplier` (number): Multiplier.

## Returns
- `result` (vector): A vector where entry `i` corresponds to the transmission
effect on variable `x_i`.

## Notes
- This function is intended for internal use only.

See also `toTransmissionIrfs`
:::
:::


    