---
title: What is the Associated Graph?
description: | 
  Transmission channels are best thought of as paths through the graph associted with the model. In this article we describe was the associated graph is. 
order: 3.5
sidebar: faq

filters: 
  - tikz
tikz: 
  cache: false

bibliography: ../../references.bib
---

{{< include ../../_math-utilities.qmd >}}

While transmission channels could be defined using potential outcomes and the [systems form](systems-form.qmd), graphs are often much more intuitive. @wegnerTCA2024 therefore introduce the associated graph $\mathcal{G}(\bB, \bOmega)$ to the systems form. As the notation hints at, the graph depends on the two matrices $\bB$ and $\bOmega$[^1] which, in turn, depend on the [dynamic form](dynamic-form.qmd). 

[^1]: For a refresher on these two matrices, check the [systems form article](systems-form.qmd) or Section 3 of @wegnerTCA2024. 

The associated graph $\mathcal{G}(\bB, \bOmega)$ has three components: 

1. A node for each shock in $\bvarepsilon$ of the systems form and, thus, a node for each shock in $\bvarepsilon_t$ of the dynamic form for each time period $t=0, \ldots, h$. @wegnerTCA2024 depict these edges uses squares. 
2. A node for each variable in $\bx$ and, thus, a node for each variable in $\by_t$ for each time period $t=0,\ldots, h$. @wegnerTCA2024 depict these nodes with circles and arrange them so that nodes corresponding to earlier time periods are ordered to the left of nodes corresponding to variables of later time periods. 
3. Directed edges going from either a shock-node to a variable-node or from a variable-node to a variable-node. 
    - An edge from $\varepsilon_i$ to $x_j$ exists whenever $\Omega_{j,i}\neq 0$. The path coefficient of that edge is then equal to $\Omega_{j,i}$. 
    - An edge from $x_i$ to $x_j$ exists whenever $B_{j,i}\neq 0$. The path coefficient of that edge is then equal to $B_{j,i}$. 

**Example: VAR(1)**

Suppose the dynamic form corresponds to a Vector Autoregression of order 1 -- a VAR(1). For $h=1$, the associated graph then has the following form. 

::: {.tikz-img}
```{.tikz}
%%| filename: svar-graph

\begin{tikzpicture}[scale=1, transform shape]
        \node[circle, draw, minimum size=1cm, line width=0.8pt] (y11) at (0, 4) {$x_1$};
        \node[circle, draw, line width=0.8pt, minimum size=1cm, black] (y21) at (0, 2) {$x_2$};
        \node[circle, draw, line width=0.8pt, minimum size=1cm, black] (y31) at (0, 0) {$x_3$};
        
        \node[circle, draw, minimum size=1cm, line width=0.8pt] (y12) at (3, 4) {$x_4$};
        \node[circle, draw, line width=0.8pt, minimum size=1cm, black] (y22) at (3, 2) {$x_5$};
        \node[circle, draw, minimum size=1cm, line width=0.8pt] (y32) at (3, 0) {$x_6$};

        
        \node[rectangle, draw=blue!50, fill=blue!20, line width=0.5pt, minimum size=0.3cm] (e11) at (-2, 4) {\textcolor{black}{$\varepsilon_{1}$}};
        \node[rectangle, draw=blue!50, fill=blue!20, line width=0.5pt, minimum size=0.3cm] (e21) at (-2, 2) {\textcolor{black}{$\varepsilon_{2}$}};
        \node[rectangle, draw=blue!50, fill=blue!20, line width=0.5pt, minimum size=0.3cm] (e31) at (-2, 0) {\textcolor{black}{$\varepsilon_{3}$}};


        \draw[-latex, line width=0.8pt, black] (y11) -- (y21);
        \draw[-latex, line width=0.8pt, black] (y11) edge[in=45, out=-45] (y31);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y31);

        
        \draw[-latex, line width=0.8pt, black] (y12) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y12) edge[in=45, out=-45] (y32);
        \draw[-latex, line width=0.8pt, black] (y22) -- (y32);

        \draw[-latex, line width=0.8pt, black] (y11) -- (y12);
        \draw[-latex, line width=0.8pt, black] (y11) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y11) -- (y32);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y12);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y32);
        \draw[-latex, line width=0.8pt, black] (y31) -- (y12);
        \draw[-latex, line width=0.8pt, black] (y31) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y31) -- (y32);

        \draw[-latex, line width=0.8pt, black] (e11) -- (y11);
        \draw[-latex, line width=0.8pt, black] (e11) -- (y21);
        \draw[-latex, line width=0.8pt, black] (e11) -- (y31);
        \draw[-latex, line width=0.8pt, black] (e21) -- (y11);
        \draw[-latex, line width=0.8pt, black] (e21) -- (y21);
        \draw[-latex, line width=0.8pt, black] (e21) -- (y31);
        \draw[-latex, line width=0.8pt, black] (e31) -- (y11);
        \draw[-latex, line width=0.8pt, black] (e31) -- (y21);
        \draw[-latex, line width=0.8pt, black] (e31) -- (y31);

        \useasboundingbox (-2, -2) rectangle (4, 4);
        
    \end{tikzpicture}
```
:::

**Example: VARMA(1,1)**

Now suppose instead that the dynamic form corresponds to a VARMA(1, 1). For $h=1$ the associated graph looks as follows. Note, compared to the VAR(1) graph, edges from shocks can skip time periods, which is indicated by the edges skipping one column of variable-nodes -- each column corresponds to one time period. 

::: {.tikz-img}
```{.tikz}
%%| filename: svarma-graph

    \begin{tikzpicture}[scale=1, transform shape]
        \node[circle, draw, minimum size=1cm, line width=0.8pt] (y11) at (0, 4) {$x_1$};
        \node[circle, draw, line width=0.8pt, minimum size=1cm, black] (y21) at (0, 2) {$x_2$};
        \node[circle, draw, line width=0.8pt, minimum size=1cm, black] (y31) at (0, 0) {$x_3$};
        
        \node[circle, draw, minimum size=1cm, line width=0.8pt] (y12) at (3, 4) {$x_4$};
        \node[circle, draw, line width=0.8pt, minimum size=1cm, black] (y22) at (3, 2) {$x_5$};
        \node[circle, draw, minimum size=1cm, line width=0.8pt] (y32) at (3, 0) {$x_6$};

        
        \node[rectangle, draw=blue!50, fill=blue!20, line width=0.5pt, minimum size=0.3cm] (e11) at (-2, 4) {\textcolor{black}{$\varepsilon_{1}$}};
        \node[rectangle, draw=blue!50, fill=blue!20, line width=0.5pt, minimum size=0.3cm] (e21) at (-2, 2) {\textcolor{black}{$\varepsilon_{2}$}};
        \node[rectangle, draw=blue!50, fill=blue!20, line width=0.5pt, minimum size=0.3cm] (e31) at (-2, 0) {\textcolor{black}{$\varepsilon_{3}$}};


        \draw[-latex, line width=0.8pt, black] (y11) -- (y21);
        \draw[-latex, line width=0.8pt, black] (y11) edge[in=45, out=-45] (y31);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y31);

        
        \draw[-latex, line width=0.8pt, black] (y12) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y12) edge[in=45, out=-45] (y32);
        \draw[-latex, line width=0.8pt, black] (y22) -- (y32);

        \draw[-latex, line width=0.8pt, black] (y11) -- (y12);
        \draw[-latex, line width=0.8pt, black] (y11) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y11) -- (y32);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y12);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y21) -- (y32);
        \draw[-latex, line width=0.8pt, black] (y31) -- (y12);
        \draw[-latex, line width=0.8pt, black] (y31) -- (y22);
        \draw[-latex, line width=0.8pt, black] (y31) -- (y32);

        \draw[-latex, line width=0.8pt, black] (e11) -- (y11);
        \draw[-latex, line width=0.8pt, black] (e11) -- (y21);
        \draw[-latex, line width=0.8pt, black] (e11) -- (y31);
        \draw[-latex, line width=0.8pt, black] (e21) -- (y11);
        \draw[-latex, line width=0.8pt, black] (e21) -- (y21);
        \draw[-latex, line width=0.8pt, black] (e21) -- (y31);
        \draw[-latex, line width=0.8pt, black] (e31) -- (y11);
        \draw[-latex, line width=0.8pt, black] (e31) -- (y21);
        \draw[-latex, line width=0.8pt, black] (e31) -- (y31);

        \draw[-latex, line width=0.8pt, black] (e11) edge[in=135, out=45] (y12);
        \draw[-latex, line width=0.8pt, black] (e11) edge[in=135, out=-45] (y22);
        \draw[-latex, line width=0.8pt, black] (e11) edge[in=115, out=-25] (y32);
        \draw[-latex, line width=0.8pt, black] (e21) edge[in=-135, out=45] (y12);
        \draw[-latex, line width=0.8pt, black] (e21) edge[in=135, out=45] (y22);
        \draw[-latex, line width=0.8pt, black] (e21) edge[in=135, out=-45] (y32);
        \draw[-latex, line width=0.8pt, black] (e31) edge[in=-115, out=25] (y12);
        \draw[-latex, line width=0.8pt, black] (e31) edge[in=-135, out=45] (y22);
        \draw[-latex, line width=0.8pt, black] (e31) edge[in=-135, out=-45] (y32);

        \useasboundingbox (-2, -2) rectangle (4, 4);
\end{tikzpicture}

```
:::


::: {.callout-note}
# Where can I find more information? 

More information can be found in Section 2 and 3 of @wegnerTCA2024. 
:::

{{< include ../../_action-read-paper.qmd >}}


