---
bibliography: "../../references.bib"
title: What is the Systems Form?
description: | 
  TCA makes use of two forms (1) the dynamic form and (2) the systems form. In this article we describe what the systems form is.  
order: 3
sidebar: faq
---

{{< include ../../_math-utilities.qmd >}}

Fixing a finite horizon $h$ and defining $\bx=(\by_t^{*'}, \dots, \by_{t+h}^{*'})'$ and $\bvarepsilon=(\bvarepsilon_t', \dots, \bvarepsilon_{t+h}')'$, @wegnerTCA2024 show that the [dynamic form](dynamic-form.qmd) can be written into the following *systems form*
$$
\bx = \bB\bx + \bOmega\bvarepsilon,
$$
where $\bB$ is lower-triangular with zeros on the diagonal, $\bOmega$ is lower-block-triangular, and both are respectively given by[^1]
$$
\begin{array}{ccc}
         \bB = \begin{bmatrix}
        \bI - \bD\bL & \bO & \dots & \bO \\
        \bD\bQ'\bA^*_1 & \bI-\bD\bL & \dots & \bO \\
        \vdots & \ddots & \ddots & \vdots \\
        \bD\bQ'\bA^*_h & \dots & \bD\bQ'\bA^*_1 & \bI - \bD\bL
    \end{bmatrix}, & \quad & 
    \bOmega = \begin{bmatrix}
        \bD\bQ' & \bO & \dots & \bO \\
        \bD\bQ'\bPsi_1 & \bD\bQ' & \dots & \bO \\
        \vdots & \ddots & \ddots & \vdots \\
        \bD\bQ'\bPsi_h & \dots & \bD\bQ'\bPsi_1 & \bD\bQ'
   \end{bmatrix},
\end{array}
$$

[^1]: For expositional ease we ommitted the dimension subscripts, letting $\bI = \bI_K$ and $\bO = \bO_K$

This system form can either be used together with potential outcomes to define transmission channels, or can be used to build an [associated graph](graphical-form.qmd) in which transmission channels are much more intuitively defined. 


::: {.callout-note}
# Where can I find more information? 

More information on the systems form and the detailed steps used to move from the dynamic to the systems form can be found in Section 3 and the Appendix of @wegnerTCA2024. 
:::

{{< include ../../_action-read-paper.qmd >}}
