---
title: What is Transmission Channel Analysis (TCA)? 
description: | 
  In this article we describe (intuitively) what TCA is and what it does. 
order: 1
sidebar: faq
bibliography: "../../references.bib"
nocite: |
  @wegnerTCA2024
---

Standard impulse response analysis only provides information about the total effect of a shock or a policy. However, two shocks or policies[^1] can have the same total effect on a variable but work in two very different ways. Thus, to distinguish between two shocks or to distinguish between two theories, pure impulse response analysis is sometimes not enough. 

[^1]: We will use shock and policy interchangeably throughout the rest.

Transmission Channel Analysis (TCA) is an analytic tool used to decompose impulse response functions into the effects along transmission channels. Transmission channels, on the other hand, are descriptions of a *how* a shock or a policy work. Thus, TCA allows to quantify the different channels or machanisms behind total effects. 

## What does TCA do (intuitively)?

Think about what happens after a contractionary monetary policy shock. The shock will increase the policy rate. Because the policy rate indirectly determines other rates, corporate bond rates will increase. Higher corporate bond rates, on the other hand, increase the funding costs of firms, but also increases the incentive to invest in corporate bonds. The former will most likely lead to lower capital investments, while the latter will lead to an increase in savings. Either of these effects will decrease aggregate demand and will thus lead to downward pressure on prices. 

Rather than describing the shocks propagation in words, we could have also used a graphical representation like the following. 

::: {.column-page}
```{mermaid}
flowchart LR
  A[Monetary policy shock] --> B[Policy rate]
  B --> C[Corporate bond rates]
  C --> D[Funding cost of firms]
  C --> E[Incentive to save]
  D --> F[Capital investments]
  E --> G[Savings]
  F --> H[Aggregate demand]
  G --> H
  H --> I[Prices]

```
:::

This graphical representation is often more intuitive since it directly shows the various paths that the shock can take to arrive at prices. Each of these paths represents one transmission channel -- or machanism -- behind the shock's total effect on prices. 

Transmission Channel Analysis uses the fact that graphs are often more intuitive and defines dynamic models in terms of graphs[^2], similar to the one above, but now including the time dimension. Channels -- descriptions of how a shock propagates through the system to a specific variable -- are then defined as paths through the graph. By tracing the effect along a subcollection of paths, i.e. by tracing the effect of the shock but ignoring some of the paths, various new insights can be gained. Moreover, by keeping track of the effects when moving from one node to another, TCA can quantify the effect along all transmission channels and can thus fully decompose the total effect. 

[^2]: @wegnerTCA2024 refer to this graph as the [associated graph](graphical-form.qmd).

::: {.callout-note}
# Want to know more?

More information about what TCA is, including small examples, can be found in Sections 1 and 2 of @wegnerTCA2024.

::: {#refs}
**How to cite TCA?**
:::

:::

{{< include ../../_action-read-paper.qmd >}}
